### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [addingwell/mediamoov-tag#1]
https://github.com/addingwell/mediamoov-tag/blob/9ca7b94748f4adaf4b0ce2081fa4efa98f470a3a/template.tpl#L205-L206

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by WFrancois** [comment]
Hey,

Thanks for the report, this is fixed!
