### ISSUE TITLE
Invalid YAML

### ISSUE THREAD

**Issue by semisight** [addingwell/mediamoov-tag#3]
https://github.com/addingwell/mediamoov-tag/blob/d7f6b2e82f3fbfc720b5121235fd70f95623203a/metadata.yaml#L5

You'll need to wrap this value in quotes like so:

```yaml
changeNotes: "Fix: Encode URI Component on all items"
```

**Comment by WFrancois** [comment]
Oops, thanks, wouldn't have notice that!
I'll check my other repo in case there's an issue like that elsewhere
